/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{vue,js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        "surface": "#121315",
        "surface-dim": "#121315",
        "surface-bright": "#38393b",
        "surface-container-lowest": "#0d0e10",
        "surface-container-low": "#1b1c1e",
        "surface-container": "#1f2022",
        "surface-container-high": "#292a2c",
        "surface-container-highest": "#343537",
        "on-surface": "#e3e2e4",
        "on-surface-variant": "#b9cacb",
        "inverse-surface": "#e3e2e4",
        "inverse-on-surface": "#303032",
        "outline": "#849495",
        "outline-variant": "#3b494b",
        "surface-tint": "#00dbe9",
        "primary": "#dbfcff",
        "on-primary": "#00363a",
        "primary-container": "#00f0ff",
        "on-primary-container": "#006970",
        "inverse-primary": "#006970",
        "secondary": "#d1bcff",
        "on-secondary": "#3c0090",
        "secondary-container": "#7000ff",
        "on-secondary-container": "#ddcdff",
        "tertiary": "#fff5de",
        "on-tertiary": "#3b2f00",
        "tertiary-container": "#fed639",
        "on-tertiary-container": "#715d00",
        "error": "#ffb4ab",
        "on-error": "#690005",
        "error-container": "#93000a",
        "on-error-container": "#ffdad6",
        "primary-fixed": "#7df4ff",
        "primary-fixed-dim": "#00dbe9",
        "on-primary-fixed": "#002022",
        "on-primary-fixed-variant": "#004f54",
        "secondary-fixed": "#e9ddff",
        "secondary-fixed-dim": "#d1bcff",
        "on-secondary-fixed": "#23005b",
        "on-secondary-fixed-variant": "#5700c9",
        "tertiary-fixed": "#ffe179",
        "tertiary-fixed-dim": "#eac324",
        "on-tertiary-fixed": "#231b00",
        "on-tertiary-fixed-variant": "#554500",
        "background": "#121315",
        "on-background": "#e3e2e4",
        "surface-variant": "#343537",
        "surface-dark": "#121315",
        "surface-light": "#F8F9FA",
        "status-low": "#00C853",
        "status-moderate": "#FFD600",
        "status-high": "#FF3D00",
        "security-alert": "#FF0033"
      },
      borderRadius: {
        "sm": "0.25rem",
        "DEFAULT": "0.5rem",
        "md": "0.75rem",
        "lg": "1rem",
        "xl": "1.5rem",
        "full": "9999px"
      },
      spacing: {
        "base": "4px",
        "xs": "4px",
        "sm": "8px",
        "md": "16px",
        "lg": "24px",
        "xl": "48px",
        "gutter": "16px",
        "margin-mobile": "16px",
        "margin-desktop": "32px"
      },
      fontFamily: {
        "display-lg": ["Geist", "sans-serif"],
        "headline-lg": ["Geist", "sans-serif"],
        "headline-md": ["Geist", "sans-serif"],
        "body-lg": ["Geist", "sans-serif"],
        "body-md": ["Geist", "sans-serif"],
        "label-lg": ["Geist", "sans-serif"],
        "label-sm": ["Geist", "sans-serif"],
        "headline-lg-mobile": ["Geist", "sans-serif"]
      },
      fontSize: {
        "display-lg": ["3rem", { lineHeight: "3.5rem", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg": ["2rem", { lineHeight: "2.5rem", fontWeight: "600" }],
        "headline-md": ["1.5rem", { lineHeight: "2rem", fontWeight: "600" }],
        "body-lg": ["1.125rem", { lineHeight: "1.75rem", fontWeight: "400" }],
        "body-md": ["1rem", { lineHeight: "1.5rem", fontWeight: "400" }],
        "label-lg": ["0.875rem", { lineHeight: "1.25rem", letterSpacing: "0.05em", fontWeight: "600" }],
        "label-sm": ["0.75rem", { lineHeight: "1rem", fontWeight: "500" }],
        "headline-lg-mobile": ["1.75rem", { lineHeight: "2.25rem", fontWeight: "600" }]
      }
    },
  },
  plugins: [],
}
